apiVersion: v1
kind: ConfigMap
metadata:
  name: leafy-org
  namespace: leafy-pay
data:
  baseUrl: http://<ops-manager-external-ip>:8080

  # Optional Parameters
  # projectName: My Ops/Cloud Manager Project

  orgId: "your-org-id"